POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
  "longUrl": "https://recruitingscience.com/job/vp-engineering-stealth-mode-startup-healthcare-tech-hipaa-full-stack-machine-learning-computer-vision-ios-android-scalable-infrastructure/"
}